#!/usr/bin/env node
/**
 * version-bump.js — run automatically via predev / prestart.
 *
 * 1. Reads package.json, increments the PATCH segment.
 * 2. Writes package.json back with the new version.
 * 3. Writes src/client/version.js so the browser bundle always
 *    reflects the current version without a build step.
 * 4. Updates the **Version** field in specs/001-better-dispute-app/constitution.md
 *    so the governing document stays in sync with the codebase.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir  = dirname(fileURLToPath(import.meta.url));
const root   = resolve(__dir, '..');

// ── 1. Bump package.json ─────────────────────────────────────────────────────
const pkgPath = resolve(root, 'package.json');
const pkg     = JSON.parse(readFileSync(pkgPath, 'utf8'));

const [major, minor, patch] = pkg.version.split('.').map(Number);
pkg.version = `${major}.${minor}.${patch + 1}`;

writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
console.log(`[version-bump] ${major}.${minor}.${patch} → ${pkg.version}`);

// ── 2. Write src/client/version.js ───────────────────────────────────────────
const versionJsPath = resolve(root, 'src/client/version.js');
writeFileSync(
  versionJsPath,
  `// Auto-generated by scripts/version-bump.js — do not edit manually.\nexport const VERSION = '${pkg.version}';\n`
);

// ── 3. Patch constitution.md **Version** row ─────────────────────────────────
const constitutionPath = resolve(root, 'specs/001-better-dispute-app/constitution.md');
let   constitution     = readFileSync(constitutionPath, 'utf8');

// Match the table row: | **Version** | `x.y.z` |
constitution = constitution.replace(
  /(\|\s*\*\*Version\*\*\s*\|\s*`)[^`]+(`)(\s*\|)/,
  `$1${pkg.version}$2$3`
);

// Also update the footer colophon line if present:
// **Version**: x.y.z | ...
constitution = constitution.replace(
  /(\*\*Version\*\*:\s*)[^\s|]+/,
  `$1${pkg.version}`
);

writeFileSync(constitutionPath, constitution);
console.log(`[version-bump] constitution.md → ${pkg.version}`);
